name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 23
        uses: actions/setup-java@v1
        with:
          java-version: 23
      - name: Test with Maven
        run: mvn test
      - name: notify-microsoft-teams
        uses: carriquiry-g/ms-teams-notification@v2
        with:
          github-token: ${{ github.token }} # this will use the runner's token.
          ms-teams-webhook-uri: ${{ secrets.MSTEAMS_WEBHOOK }}
          notification-summary: A new build was started.
          notification-style: good
          timezone: America/Chicago
          verbose-logging: true
